<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<div class="alert fade in">
  <a class="close" data-dismiss="alert">×</a>
  <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<div class="category-products span9">
    <?php echo $this->getToolbarHtml() ?>
    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php
      $i=0;
      $span = "span" . ((12-(12%$_columnCount))/$_columnCount);
      foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid row-fluid thumbnails">
        <?php endif ?>
          <li class="item <?php echo $span;  if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> ">
            <div class="thumbnail">
              <?php
                $_images = Mage::getModel('catalog/product')->load( $_product->getId() )->getMediaGalleryImages();
                $_collection = "";
                $i = 0;
                foreach( $_images as $_image) {
                  $_collection = '<a href="'. $_product->getProductUrl() .'" title="'. $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) .'">
                    <img class="pic'. (($i++ == 0) ? ' last' : '') .'" src="'. $this->helper('catalog/image')->init( $_product, 'thumbnail', $_image->getFile() )->resize(300) .'" alt="'. $this->htmlEscape( $_image->getLabel() ) .'" />
                  </a>' . $_collection;
                }
                echo $_collection;
              ?>
              <div class="description">
                <p><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></p>
                <p><strong>1950 руб.</strong></p>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                  <hr/>
                  <div style="text-align: center;"><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></div>
                <?php endif; ?>
              </div>
            </div>
          </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('div.products-grid'), ['odd','even','first','last'])</script>

    <div class="toolbar-bottom"><?php echo $this->getToolbarHtml() ?></div>
</div>
<?php endif; ?>
